### ISSUE TITLE
Add `schema-b` artificats currently on corpus generator's repo to artifacts in `elastic-package` for rally benchmark command

### ISSUE THREAD

**Issue by aspacca** [elastic/elastic-package#1476]
```[tasklist]
### Tasks
- [x] [aws.billing](https://github.com/elastic/elastic-integration-corpus-generator-tool/tree/main/assets/templates/aws.billing/schema-b) - [PR](https://github.com/elastic/integrations/pull/8403)
- [x] [aws.ec2_logs](https://github.com/elastic/elastic-integration-corpus-generator-tool/tree/main/assets/templates/aws.ec2_logs/schema-b) - [PR](https://github.com/elastic/integrations/pull/8416)
- [x] [aws.ec2_metrics](https://github.com/elastic/elastic-integration-corpus-generator-tool/tree/main/assets/templates/aws.ec2_metrics/schema-b) - [PR](https://github.com/elastic/integrations/pull/8442)
- [x] [aws.sqs](https://github.com/elastic/elastic-integration-corpus-generator-tool/tree/main/assets/templates/aws.sqs/schema-b) - [PR](https://github.com/elastic/integrations/pull/8429)
- [x] [kubernetes.container](https://github.com/elastic/elastic-integration-corpus-generator-tool/tree/main/assets/templates/kubernetes.container) - [PR](https://github.com/elastic/integrations/pull/8444)
- [x] [kubernetes.pod](https://github.com/elastic/elastic-integration-corpus-generator-tool/tree/main/assets/templates/kubernetes.pod) - [PR](https://github.com/elastic/integrations/pull/8443)
```
