### ISSUE TITLE
Add options to test with stacks with minimal versions and capabilities

### ISSUE THREAD

**Issue by jsoriano** [elastic/elastic-package#1520]
Packages include restrictions on the stacks where they are intended to be used. Mainly:
* `kibana.version`, for the minimal version where the package can be used.
* `elastic.capabilities`, for the capabilities the stack must have to properly use the package.

It would be nice to have ways to easily start stacks with the proper restrictions for each package, to ease testing and development.

For the kibana version, we have some code in CI, that we could migrate to elastic-package: https://github.com/elastic/integrations/blob/95f7a344da4f314e86d0f4066a41c457c7c9f9d9/.ci/Jenkinsfile#L385

UX
--

The UI could be through user parameters, and would be dependant of the current package. So for example the following command, when executed with a package with `kibana.version: ^8.8.0`, will start stack 8.8.0:
```
elastic-package stack up -d -U stack.auto_strict_version=true
```

Similar for capabilities. In this case, we should define a set of settings in the [kibana config files](https://github.com/elastic/kibana/tree/71bbbacd594885553ae10fc964ad1be9e0f63cf2/config) that enable or disable capabilities supported by packages. For example with the following command, and a package with the `elastic.capabilities: [security]`, it will start a "vanilla" stack, with `xpack.securitySolutionServerless.enabled: true`:
```
elastic-package stack up -d -U stack.auto_strict_capabilities=true
```

Alternatively, we can add explicit flags, for example the following ones, though they would only work with some providers:
```
elastic-package stack up -d --version package
```
```
elastic-package stack up -d --capabilities package
```

Default behavior
--

Once these options are in place, should we enable them by default when running `elastic-package stack up` from a package directory?

In that case, it should be also possible to reconfigure/replace the stack when running `elastic-package stack up` from a different directory.

Also, it would be nice to add something about the capabilities enabled in `elastic-package stack status`.

```[tasklist]
### Tasks
- [ ] Add option to automatically select version from current package.
- [ ] Replace implementation in CI pipeline with this new option.
- [ ] Add option to automatically configure capabilities required by current package.
- [ ] Use these options in CI.
- [ ] Enable these settings automatically when running `stack up` from packages directory?
- [ ] Add information about this to `elastic-package stack status`.
```

**Comment by kpollich** [comment]
We haven't revisited this issue in a while, so we're closing it due to inactivity. Please reopen with a comment if you think this is a mistake. Thanks!
