### ISSUE TITLE
[meta] Improve system tests robustness

### ISSUE THREAD

**Issue by marc-gr** [elastic/elastic-package#1537]
Several integrations that rely on external APIs use `stream` as their test services to build mocks and run system tests.

There are some blind spots when it comes to detecting config errors that could lead to wrong pagination, infinite pagination loops, etc. mainly caused by the inability of `elastic-package` to detect anything else than `is there any data?` in the data stream or `is there the expected number of events?` if `assert.hit_count` is set, which makes things better but is not enough.

As part of an effort to improve system tests robustness some things could be improved:

- [ ] Add an option to `data_stream/_dev/test/system/config.yml` to fail the tests if the test services exit unsuccessfully. https://github.com/elastic/elastic-package/pull/1540
- [x] https://github.com/elastic/stream/issues/61
- [x] https://github.com/elastic/stream/issues/62

Once this is done we can leverage these new behavior for system tests that require it.
