### ISSUE TITLE
Performance testing for ingest pipelines

### ISSUE THREAD

**Issue by adriansr** [elastic/elastic-package#855]
This is a proposed first iteration of performance benchmarks for Elastic packages, part of a broader effort to provide tooling to fully understand the performance or storage impacts of changes to ingest pipelines and other assets.

The objective of this iteration is to provide visibility into a package's ingest-pipelines performance for a developer working on a package. To achieve this, it makes use of existing facilities and data already available to `elastic-package` in order to reduce development time and cross-team dependencies:

- Uses existing [Elasticsearch's Nodes Stats API ](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html), already used by `elastic-package` for pipeline coverage.
- Uses existing testing logs/documents from ingest pipeline tests.
- Reports it's output to stdout in a format similar to tests.
- Works as an additional stage for pipeline tests (i.e. `elastic-package test pipeline --bench`), in opposition to a completely new action in elastic-agent (`elastic-package benchmark pipeline`). This reduces code complexity.

### First stage

- [x] Add performance measurement to package's pipeline tests (`--bench`). #958
- [x] Text output: Raw (eps) performance, top N ingest processors by time spent. #958
- ~~[ ] IP address randomization to properly exercise geoip processors.~~ Unfeasible with pipeline tests, as only a limited number of IP addresses is allowed.

### Further development

- [x] xUnit output for CI reports. Needs investigation as benchmark representation in xUnit is not clearly specified and may need a bit of trial and error. #958 (will need improvements).
- ~[ ] #1040~

**Comment by marc-gr** [comment]
> * [ ]  Benchmarking against previous package version. Need to figure out what's the best way to implement this, possibly just comparing the output of two benchmark runs, similar to Go's benchcmp / [benchstat.](https://pkg.go.dev/golang.org/x/perf/cmd/benchstat)

This requires to add the git commit as part of the registry metadata (https://github.com/elastic/package-spec/issues/446)

**Comment by marc-gr** [comment]
Moved last point to https://github.com/elastic/elastic-package/issues/1040 as it is blocked and requires of specific work and is out of the first stage
